### PR TITLE
Fix compiling on windows and some error fix (nw)

### PR DESCRIPTION
**Pull request by mmicko**
resolves issue with strndup availability, fixes issue of route_compare_method.c compiling

### CODE REVIEW

**Comment by nmdguerreiro** [comment]
@kellabyte Do we want to merge this one or #92?

**Comment by kellabyte** [comment]
I think I like this one better. What do you think? I'm kind of torn whether I want to support VS2008 and it's weird C standard support though. It's going to kind of make the code base ugly. I think I'm okay with supporting Windows but newer Visual Studio compiler versions that don't make the whole thing complicated.

I'll merge this one.

**Comment by SajayAntony** [comment]
Ok now time to benchmark this.

**Comment by kellabyte** [comment]
I didn't do a benchmark because I figured it was pretty harmless. Am I wrong? I don't have the before/after comparison but here's the after.

```
Running 10s test @ http://server:8000
  40 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.28ms   52.23ms   1.69s    94.56%
    Req/Sec   127.07k    41.48k  290.75k    70.97%
  Latency Distribution
     50%    6.32ms
     75%   18.23ms
     90%   37.69ms
     99%    0.00us
  50762199 requests in 10.10s, 8.32GB read
  Socket errors: connect 0, read 177, write 0, timeout 0
  Non-2xx or 3xx responses: 1487
Requests/sec: 5026888.03
Transfer/sec:    843.71MB
```

**Comment by SajayAntony** [comment]
No concerns. Looks like it still clocks at 5 million rps. Curious, what's the CPU spec.

**Pull request merged**
